### ISSUE TITLE
Arena temporarily spawning in the lobby

### ISSUE THREAD

**Issue by cj1705** [Realizedd/DE-ArenaRegen#7]
Hi!

I'm currently trying to set up the extension on 1.17.1 paper. When a duel is over, the selected regen area of that arena appears in the set lobby. But, after switching servers/disconnecting from the server, the lobby appears to be restored. This is shown for, as far as I know, the people within the duel only.

Heres a video showing the issue, 
[https://youtu.be/SBGbIx3mhI4](url)

Any tips?

**Comment by Realizedd** [comment]
Should be fixed in bebabf6. Thanks for reporting.
